### ISSUE TITLE
error: bundling failed: Error: Unable to resolve module `stream` from hash-base

### ISSUE THREAD

**Issue by romreed** [crypto-browserify/hash-base#13]
At react native i got this error

`error: bundling failed: Error: Unable to resolve module `stream` from `/Users/reed/WebstormProjects/solitaire/node_modules/hash-base/index.js`: Module `stream` does not exist in the Haste module map

This might be related to https://github.com/facebook/react-native/issues/4968
To resolve try the following:
  1. Clear watchman watches: `watchman watch-del-all`.
  2. Delete the `node_modules` folder: `rm -rf node_modules && npm install`.
  3. Reset Metro Bundler cache: `rm -rf /tmp/metro-bundler-cache-*` or `npm start -- --reset-cache`.
  4. Remove haste cache: `rm -rf /tmp/haste-map-react-native-packager-*`.
    at ModuleResolver.resolveDependency (/Users/reed/WebstormProjects/solitaire/node_modules/metro/src/node-haste/DependencyGraph/ModuleResolution.js:139:15)
    at ResolutionRequest.resolveDependency (/Users/reed/WebstormProjects/solitaire/node_modules/metro/src/node-haste/DependencyGraph/ResolutionRequest.js:49:18)
    at DependencyGraph.resolveDependency (/Users/reed/WebstormProjects/solitaire/node_modules/metro/src/node-haste/DependencyGraph.js:219:16)
    at Object.resolve (/Users/reed/WebstormProjects/solitaire/node_modules/metro/src/lib/transformHelpers.js:141:30)
    at dependencies.map.result (/Users/reed/WebstormProjects/solitaire/node_modules/metro/src/DeltaBundler/traverseDependencies.js:373:31)
    at Array.map (<anonymous>)
    at resolveDependencies (/Users/reed/WebstormProjects/solitaire/node_modules/metro/src/DeltaBundler/traverseDependencies.js:369:18)
    at /Users/reed/WebstormProjects/solitaire/node_modules/metro/src/DeltaBundler/traverseDependencies.js:188:33
    at Generator.next (<anonymous>)
    at step (/Users/reed/WebstormProjects/solitaire/node_modules/metro/src/DeltaBundler/traverseDependencies.js:298:30)
`

**Comment by maxammann** [comment]
This module depends on node.js. Therefore it is incompatible with RN

**Comment by fanatid** [comment]
Probably should be resolved with #14 (3.1.0)
